/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Changes the fields that are sent: settings, guidelines and the script.
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/voiceover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Voiceover
         * @description Stores the voiceover (WAV, MP3, M4A or FLAC) sent as the raw request body.
         *
         *     A new upload becomes the project's voiceover. The previous file is kept.
         */
        post: operations["upload_voiceover_api_projects__project_id__voiceover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Settings */
        get: operations["list_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Setting */
        put: operations["save_setting_api_settings__key__put"];
        post?: never;
        /**
         * Reset Setting
         * @description Removes the saved value, so the environment or built-in value applies again.
         */
        delete: operations["reset_setting_api_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connection
         * @description The last stored test result. Reads the database only, never calls the server.
         */
        get: operations["get_connection_api_gpu_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/connection/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Tests the saved GPU server URL now, then checks its API if it answered.
         *
         *     An unreachable server is a normal 200 answer.
         */
        post: operations["test_connection_api_gpu_connection_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description The stored state the banner reads. Reads the database only, never calls the server.
         */
        get: operations["get_status_api_gpu_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Contract Sources
         * @description Saves the list of sources whose answers are recorded and checked.
         */
        put: operations["save_contract_sources_api_gpu_contract_sources_put"];
        post?: never;
        /**
         * Reset Contract Sources
         * @description Removes the saved list, so the built-in sources apply again.
         */
        delete: operations["reset_contract_sources_api_gpu_contract_sources_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description The approved API, any change waiting for approval, and the last check.
         *
         *     Reads the database only, never calls the server, and never returns whole documents.
         */
        get: operations["get_contract_api_gpu_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Contract
         * @description Records the API as it is now, if every source answers the same twice.
         *
         *     Takes a few seconds: each source is fetched twice, a few seconds apart. A refused
         *     approval is a normal 200 answer with `approved: false` and a reason per source.
         */
        post: operations["approve_contract_api_gpu_contract_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Expected */
            expected?: {
                [key: string]: string;
            };
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Approved */
            approved: boolean;
            /** Sources */
            sources: components["schemas"]["SourceApprovalOut"][];
        };
        /** ApprovedSummaryOut */
        ApprovedSummaryOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Fingerprint */
            fingerprint: string;
            /** Server Content Hash */
            server_content_hash: string | null;
            /** Api Version */
            api_version: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Approved At */
            approved_at: string | null;
            /** Operation Count */
            operation_count: number | null;
            /** Tags */
            tags: components["schemas"]["TagGroupOut"][];
        };
        /** ConnectionState */
        ConnectionState: {
            last_test: components["schemas"]["ConnectionTest"] | null;
        };
        /** ConnectionTest */
        ConnectionTest: {
            /** Reachable */
            reachable: boolean;
            /** Called Url */
            called_url: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Http Status */
            http_status: number | null;
            /** Default Partition */
            default_partition: string | null;
            /** Error */
            error: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            health: components["schemas"]["ConnectionTest"];
            contract: components["schemas"]["ContractCheckOut"] | null;
        };
        /** ContractCheckOut */
        ContractCheckOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "changed" | "not_approved" | "unreachable";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Sources */
            sources: components["schemas"]["SourceCheckOut"][];
        };
        /** ContractDiffOut */
        ContractDiffOut: {
            /** Entries */
            entries: components["schemas"]["DiffEntryOut"][];
            /** Truncated */
            truncated: boolean;
            openapi: components["schemas"]["OpenApiChangesOut"] | null;
        };
        /** ContractOverviewOut */
        ContractOverviewOut: {
            sources_setting: components["schemas"]["ContractSourcesOut"];
            last_check: components["schemas"]["ContractCheckOut"] | null;
            /** Sources */
            sources: components["schemas"]["SourceOverviewOut"][];
        };
        /** ContractSourceIn */
        ContractSourceIn: {
            /** Name */
            name: string;
            /** Base */
            base: string;
            /** Path */
            path: string;
        };
        /** ContractSourceOut */
        ContractSourceOut: {
            /** Name */
            name: string;
            /**
             * Base
             * @enum {string}
             */
            base: "gpu" | "transcription";
            /** Path */
            path: string;
            /** Called Url */
            called_url: string;
        };
        /** ContractSourcesOut */
        ContractSourcesOut: {
            /** Sources */
            sources: components["schemas"]["ContractSourceOut"][];
            /**
             * Source
             * @enum {string}
             */
            source: "saved" | "built_in";
            /** Updated At */
            updated_at: string | null;
            /** Note */
            note: string | null;
        };
        /** ContractSourcesUpdate */
        ContractSourcesUpdate: {
            /** Sources */
            sources: components["schemas"]["ContractSourceIn"][];
        };
        /** ContractStatusOut */
        ContractStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "changed" | "not_approved" | "unreachable" | "unknown";
            /** Checked At */
            checked_at: string | null;
            /** Sources */
            sources: components["schemas"]["SourceCheckOut"][];
            /** Message */
            message: string | null;
        };
        /** DatabaseStatus */
        DatabaseStatus: {
            /** Ok */
            ok: boolean;
            /** Journal Mode */
            journal_mode?: string | null;
            /** Foreign Keys */
            foreign_keys?: number | null;
            /** Revision */
            revision?: string | null;
        };
        /** DiffEntryOut */
        DiffEntryOut: {
            /** Path */
            path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "changed";
            /** Before */
            before: string | null;
            /** After */
            after: string | null;
            /** Text Diff */
            text_diff: string[] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** GpuStatus */
        GpuStatus: {
            server: components["schemas"]["ServerStatusOut"];
            contract: components["schemas"]["ContractStatusOut"];
            /** Waiting Jobs */
            waiting_jobs: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            database: components["schemas"]["DatabaseStatus"];
            ffmpeg: components["schemas"]["ToolStatus"];
            ffprobe: components["schemas"]["ToolStatus"];
        };
        /** OpenApiChangesOut */
        OpenApiChangesOut: {
            /** Operations Added */
            operations_added: string[];
            /** Operations Removed */
            operations_removed: string[];
            /** Operations Changed */
            operations_changed: string[];
            /** Schemas Added */
            schemas_added: string[];
            /** Schemas Removed */
            schemas_removed: string[];
            /** Schemas Changed */
            schemas_changed: string[];
        };
        /** OperationOut */
        OperationOut: {
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Summary */
            summary: string | null;
        };
        /** PendingChangeOut */
        PendingChangeOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Fingerprint */
            fingerprint: string;
            /** Api Version */
            api_version: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            diff: components["schemas"]["ContractDiffOut"];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gen Width */
            gen_width: number;
            /** Gen Height */
            gen_height: number;
            /** Out Width */
            out_width: number;
            /** Out Height */
            out_height: number;
            /** Fps */
            fps: number;
            /** Min Scene Seconds */
            min_scene_seconds: number;
            /** Max Scene Seconds */
            max_scene_seconds: number;
            /** Clip Sound Volume */
            clip_sound_volume: number;
            /** Style Prefix */
            style_prefix: string | null;
            /** Prompt Suffix */
            prompt_suffix: string | null;
            /** Negative Prompt */
            negative_prompt: string | null;
            /** Cut Instructions */
            cut_instructions: string | null;
            /** Script Text */
            script_text: string | null;
            voiceover: components["schemas"]["VoiceoverOut"] | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Voiceover Duration S */
            voiceover_duration_s: number | null;
            /** Has Script */
            has_script: boolean;
        };
        /**
         * ProjectUpdate
         * @description Only the fields that are sent are changed. The orientation cannot be changed.
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Gen Width */
            gen_width?: number | null;
            /** Gen Height */
            gen_height?: number | null;
            /** Out Width */
            out_width?: number | null;
            /** Out Height */
            out_height?: number | null;
            /** Fps */
            fps?: number | null;
            /** Min Scene Seconds */
            min_scene_seconds?: number | null;
            /** Max Scene Seconds */
            max_scene_seconds?: number | null;
            /** Clip Sound Volume */
            clip_sound_volume?: number | null;
            /** Style Prefix */
            style_prefix?: string | null;
            /** Prompt Suffix */
            prompt_suffix?: string | null;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Cut Instructions */
            cut_instructions?: string | null;
            /** Script Text */
            script_text?: string | null;
        };
        /** SecretStatus */
        SecretStatus: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Is Set */
            is_set: boolean;
        };
        /** ServerStatusOut */
        ServerStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "reachable" | "unreachable" | "unknown";
            /** Checked At */
            checked_at: string | null;
            /** Called Url */
            called_url: string | null;
            /** Error */
            error: string | null;
        };
        /** SettingItem */
        SettingItem: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Label */
            label: string;
            /** Help */
            help: string;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "string" | "integer";
            /** Value */
            value: string | number;
            /**
             * Source
             * @enum {string}
             */
            source: "saved" | "environment" | "built_in";
            /** Default */
            default: string | number;
            /** Env Var */
            env_var: string | null;
            /** Allow Blank */
            allow_blank: boolean;
            /** Min Value */
            min_value: number | null;
            /** Max Value */
            max_value: number | null;
            /** Will Call */
            will_call: string | null;
            /** Note */
            note: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SettingUpdate */
        SettingUpdate: {
            /** Value */
            value: number | string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Settings */
            settings: components["schemas"]["SettingItem"][];
            /** Secrets */
            secrets: components["schemas"]["SecretStatus"][];
        };
        /** SourceApprovalOut */
        SourceApprovalOut: {
            /** Name */
            name: string;
            /** Called Url */
            called_url: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "approved" | "unchanged" | "unstable" | "changed_again" | "unreachable" | "unreadable";
            /** Message */
            message: string | null;
            /** Fingerprint */
            fingerprint: string | null;
            diff: components["schemas"]["ContractDiffOut"] | null;
        };
        /** SourceCheckOut */
        SourceCheckOut: {
            /** Name */
            name: string;
            /** Called Url */
            called_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "changed" | "not_approved" | "unreachable" | "unreadable";
            /** Message */
            message: string | null;
            /** Approved Fingerprint */
            approved_fingerprint: string | null;
            /** Current Fingerprint */
            current_fingerprint: string | null;
        };
        /** SourceOverviewOut */
        SourceOverviewOut: {
            /** Name */
            name: string;
            /**
             * Base
             * @enum {string}
             */
            base: "gpu" | "transcription";
            /** Path */
            path: string;
            /** Called Url */
            called_url: string;
            approved: components["schemas"]["ApprovedSummaryOut"] | null;
            pending: components["schemas"]["PendingChangeOut"] | null;
            last_check: components["schemas"]["SourceCheckOut"] | null;
        };
        /** TagGroupOut */
        TagGroupOut: {
            /** Tag */
            tag: string;
            /** Operations */
            operations: components["schemas"]["OperationOut"][];
        };
        /** ToolStatus */
        ToolStatus: {
            /** Ok */
            ok: boolean;
            /** Version */
            version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceoverOut */
        VoiceoverOut: {
            /** Asset Id */
            asset_id: number;
            /** Url */
            url: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Duration S */
            duration_s: number | null;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Something is not OK. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description A value breaks a rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A value breaks a rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_voiceover_api_projects__project_id__voiceover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is larger than the limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not sent as application/octet-stream. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is not an acceptable voiceover. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    save_setting_api_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingItem"];
                };
            };
            /** @description No setting has this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The value is not valid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_setting_api_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingItem"];
                };
            };
            /** @description No setting has this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_gpu_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionState"];
                };
            };
        };
    };
    test_connection_api_gpu_connection_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
        };
    };
    get_status_api_gpu_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuStatus"];
                };
            };
        };
    };
    save_contract_sources_api_gpu_contract_sources_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractSourcesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSourcesOut"];
                };
            };
            /** @description The value is not valid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_contract_sources_api_gpu_contract_sources_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSourcesOut"];
                };
            };
        };
    };
    get_contract_api_gpu_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOverviewOut"];
                };
            };
        };
    };
    approve_contract_api_gpu_contract_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
