/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Changes the fields that are sent: settings, guidelines and the script.
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/voiceover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Voiceover
         * @description Stores the voiceover (WAV, MP3, M4A or FLAC) sent as the raw request body.
         *
         *     A new upload becomes the project's voiceover. The previous file is kept.
         */
        post: operations["upload_voiceover_api_projects__project_id__voiceover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Settings */
        get: operations["list_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Setting */
        put: operations["save_setting_api_settings__key__put"];
        post?: never;
        /**
         * Reset Setting
         * @description Removes the saved value, so the environment or built-in value applies again.
         */
        delete: operations["reset_setting_api_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connection
         * @description The last stored test result. Reads the database only, never calls the server.
         */
        get: operations["get_connection_api_gpu_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/connection/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Tests the saved GPU server URL now, then checks its API if it answered.
         *
         *     An unreachable server is a normal 200 answer.
         */
        post: operations["test_connection_api_gpu_connection_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description The stored state the banner reads. Reads the database only, never calls the server.
         */
        get: operations["get_status_api_gpu_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Contract Sources
         * @description Saves the list of sources whose answers are recorded and checked.
         */
        put: operations["save_contract_sources_api_gpu_contract_sources_put"];
        post?: never;
        /**
         * Reset Contract Sources
         * @description Removes the saved list, so the built-in sources apply again.
         */
        delete: operations["reset_contract_sources_api_gpu_contract_sources_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description The approved API, any change waiting for approval, and the last check.
         *
         *     Reads the database only, never calls the server, and never returns whole documents.
         */
        get: operations["get_contract_api_gpu_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/contract/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Contract
         * @description Records the API as it is now, if every source answers the same twice.
         *
         *     Takes a few seconds: each source is fetched twice, a few seconds apart. A refused
         *     approval is a normal 200 answer with `approved: false` and a reason per source.
         */
        post: operations["approve_contract_api_gpu_contract_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs, newest first: all of them, or those of one project.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancels a job that has not started, one the GPU server no longer knows, or a running
         *     clip job (which is cancelled on the GPU server first).
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resubmit Job
         * @description Queues a job the GPU server does not know again, as a new attempt.
         */
        post: operations["resubmit_job_api_jobs__job_id__resubmit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Transcription
         * @description Starts transcribing the voiceover, or returns the job that is already active.
         */
        post: operations["start_transcription_api_projects__project_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transcription
         * @description The newest transcribe job and transcript of the project. Reads the database only.
         */
        get: operations["get_transcription_api_projects__project_id__transcription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/propose-scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Scenes
         * @description Starts proposing scenes (a paid call to the language model), or returns the proposal
         *     that is already active. The same request as an earlier one reuses its stored answer
         *     unless `run_again` is sent.
         */
        post: operations["propose_scenes_api_projects__project_id__propose_scenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/draft-descriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Descriptions
         * @description Starts drafting the scene descriptions (a paid call to the language model), or returns
         *     the draft that is already active. The same request as an earlier one reuses its stored
         *     answer unless `run_again` is sent. Text the user wrote is never overwritten.
         */
        post: operations["draft_descriptions_api_projects__project_id__draft_descriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenes
         * @description The project's scenes and the proposal they came from. Reads the database only.
         */
        get: operations["get_scenes_api_projects__project_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/edit-cut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Cut
         * @description Adds, removes or moves one cut, and returns the scenes as they are afterwards.
         *
         *     Only the scenes next to the cut are rebuilt. An added or moved cut is a manual cut,
         *     timed in the middle of the gap. When a scene the edit changes has a description, frames
         *     or a clip, nothing happens until the request sets `discard_inputs`: then those inputs
         *     are cleared (their files stay on disk).
         */
        post: operations["edit_cut_api_projects__project_id__edit_cut_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Scene
         * @description Saves the scene's description and frame descriptions that are sent. Each one that
         *     changes is marked as written by the author (`manual`).
         */
        patch: operations["update_scene_api_projects__project_id__scenes__scene_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}/frames/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Frame
         * @description Stores a PNG, JPEG or WebP image sent as the raw request body as the scene's first or
         *     last frame. A frame already there is replaced; its file stays on disk.
         */
        post: operations["upload_frame_api_projects__project_id__scenes__scene_id__frames__slot__post"];
        /**
         * Remove Frame
         * @description Clears the scene's first or last frame. The asset row and the file stay.
         */
        delete: operations["remove_frame_api_projects__project_id__scenes__scene_id__frames__slot__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/frames/{asset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Frame Preview
         * @description The stored frame normalised to `width` x `height`, which must be the project's
         *     current generation size.
         */
        get: operations["frame_preview_api_projects__project_id__frames__asset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Clip
         * @description Starts generating a clip for the scene (Generate, and Regenerate when it has one).
         *
         *     A scene that already has a clip being generated returns that job: two quick clicks make
         *     one job. Each new job gets its own random seed, so it makes a new take.
         */
        post: operations["generate_clip_api_projects__project_id__scenes__scene_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/generate-ready-scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Ready Scenes
         * @description Starts a clip for every scene that is ready, has no clip yet and has no job running.
         *
         *     All the jobs are created in one transaction. The page asks before calling this, and it
         *     shows how many it will start (`ScenesOut.generate_ready_count`).
         */
        post: operations["generate_ready_scenes_api_projects__project_id__generate_ready_scenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}/select-take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Take
         * @description Makes one of the scene's finished clips the one the final video uses.
         */
        post: operations["select_take_api_projects__project_id__scenes__scene_id__select_take_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}/clip-sound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Clip Sound
         * @description Switches the scene's own clip sound on or off for the final video (Phase 10 reads it).
         */
        put: operations["set_clip_sound_api_projects__project_id__scenes__scene_id__clip_sound_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Render
         * @description Starts rendering the final video from the selected take of every scene, or returns
         *     the render that is already queued or running (two quick clicks make one job).
         */
        post: operations["start_render_api_projects__project_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Renders
         * @description The project's newest render job and its finished renders. Reads the database only.
         */
        get: operations["get_renders_api_projects__project_id__renders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Expected */
            expected?: {
                [key: string]: string;
            };
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Approved */
            approved: boolean;
            /** Sources */
            sources: components["schemas"]["SourceApprovalOut"][];
        };
        /** ApprovedSummaryOut */
        ApprovedSummaryOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Fingerprint */
            fingerprint: string;
            /** Server Content Hash */
            server_content_hash: string | null;
            /** Api Version */
            api_version: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Approved At */
            approved_at: string | null;
            /** Operation Count */
            operation_count: number | null;
            /** Tags */
            tags: components["schemas"]["TagGroupOut"][];
        };
        /** ChecksOut */
        ChecksOut: {
            /** Entries */
            entries: number;
            /** Exact */
            exact: number;
            /** Moved */
            moved: number;
            /** Flagged */
            flagged: number;
            /** Dropped */
            dropped: number;
        };
        /** ClipSoundRequest */
        ClipSoundRequest: {
            /** Use Clip Sound */
            use_clip_sound: boolean;
        };
        /** ConnectionState */
        ConnectionState: {
            last_test: components["schemas"]["ConnectionTest"] | null;
        };
        /** ConnectionTest */
        ConnectionTest: {
            /** Reachable */
            reachable: boolean;
            /** Called Url */
            called_url: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Http Status */
            http_status: number | null;
            /** Default Partition */
            default_partition: string | null;
            /** Error */
            error: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            health: components["schemas"]["ConnectionTest"];
            contract: components["schemas"]["ContractCheckOut"] | null;
        };
        /** ContractCheckOut */
        ContractCheckOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "changed" | "not_approved" | "unreachable";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Sources */
            sources: components["schemas"]["SourceCheckOut"][];
        };
        /** ContractDiffOut */
        ContractDiffOut: {
            /** Entries */
            entries: components["schemas"]["DiffEntryOut"][];
            /** Truncated */
            truncated: boolean;
            openapi: components["schemas"]["OpenApiChangesOut"] | null;
        };
        /** ContractOverviewOut */
        ContractOverviewOut: {
            sources_setting: components["schemas"]["ContractSourcesOut"];
            last_check: components["schemas"]["ContractCheckOut"] | null;
            /** Sources */
            sources: components["schemas"]["SourceOverviewOut"][];
        };
        /** ContractSourceIn */
        ContractSourceIn: {
            /** Name */
            name: string;
            /** Base */
            base: string;
            /** Path */
            path: string;
        };
        /** ContractSourceOut */
        ContractSourceOut: {
            /** Name */
            name: string;
            /**
             * Base
             * @enum {string}
             */
            base: "gpu" | "transcription";
            /** Path */
            path: string;
            /** Called Url */
            called_url: string;
        };
        /** ContractSourcesOut */
        ContractSourcesOut: {
            /** Sources */
            sources: components["schemas"]["ContractSourceOut"][];
            /**
             * Source
             * @enum {string}
             */
            source: "saved" | "built_in";
            /** Updated At */
            updated_at: string | null;
            /** Note */
            note: string | null;
        };
        /** ContractSourcesUpdate */
        ContractSourcesUpdate: {
            /** Sources */
            sources: components["schemas"]["ContractSourceIn"][];
        };
        /** ContractStatusOut */
        ContractStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "changed" | "not_approved" | "unreachable" | "unknown";
            /** Checked At */
            checked_at: string | null;
            /** Sources */
            sources: components["schemas"]["SourceCheckOut"][];
            /** Message */
            message: string | null;
        };
        /**
         * CutEditRequest
         * @description One edit of one cut. A cut is named by the number of the last word of the scene it
         *     ends, so "after word 12" is the gap between word 12 and word 13.
         */
        CutEditRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "add" | "remove" | "move";
            /** After Word */
            after_word: number;
            /** To After Word */
            to_after_word?: number | null;
            /**
             * Discard Inputs
             * @default false
             */
            discard_inputs: boolean;
        };
        /** DatabaseStatus */
        DatabaseStatus: {
            /** Ok */
            ok: boolean;
            /** Journal Mode */
            journal_mode?: string | null;
            /** Foreign Keys */
            foreign_keys?: number | null;
            /** Revision */
            revision?: string | null;
        };
        /** DiffEntryOut */
        DiffEntryOut: {
            /** Path */
            path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "changed";
            /** Before */
            before: string | null;
            /** After */
            after: string | null;
            /** Text Diff */
            text_diff: string[] | null;
        };
        /**
         * DraftDescriptionsRequest
         * @description What the user has confirmed. Every flag is off unless sent.
         */
        DraftDescriptionsRequest: {
            /**
             * Run Again
             * @default false
             */
            run_again: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * FrameOut
         * @description A scene's first or last frame: the original upload, and how it will be framed.
         */
        FrameOut: {
            /** Asset Id */
            asset_id: number;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Original Url */
            original_url: string;
            /** Preview Url */
            preview_url: string;
            /** Warnings */
            warnings: string[];
        };
        /** GenerateReadyOut */
        GenerateReadyOut: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Created */
            created: number;
        };
        /** GpuStatus */
        GpuStatus: {
            server: components["schemas"]["ServerStatusOut"];
            contract: components["schemas"]["ContractStatusOut"];
            /** Waiting Jobs */
            waiting_jobs: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            database: components["schemas"]["DatabaseStatus"];
            ffmpeg: components["schemas"]["ToolStatus"];
            ffprobe: components["schemas"]["ToolStatus"];
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Project Name */
            project_name: string;
            /** Scene Id */
            scene_id: number | null;
            /** Scene Index */
            scene_index: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "transcribe" | "plan_scenes" | "draft_descriptions" | "generate_clip" | "render_final";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Phase */
            phase: string | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "gpu" | "llm" | "local";
            /** Attempt */
            attempt: number;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Can Cancel */
            can_cancel: boolean;
            /** Can Resubmit */
            can_resubmit: boolean;
            /** Provider Job Id */
            provider_job_id: string | null;
            /** Input */
            input: unknown;
            /** Output */
            output: unknown;
            /** Result Asset Id */
            result_asset_id: number | null;
        };
        /** JobSummary */
        JobSummary: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Project Name */
            project_name: string;
            /** Scene Id */
            scene_id: number | null;
            /** Scene Index */
            scene_index: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "transcribe" | "plan_scenes" | "draft_descriptions" | "generate_clip" | "render_final";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Phase */
            phase: string | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "gpu" | "llm" | "local";
            /** Attempt */
            attempt: number;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Can Cancel */
            can_cancel: boolean;
            /** Can Resubmit */
            can_resubmit: boolean;
        };
        /** LlmInfoOut */
        LlmInfoOut: {
            /** Model */
            model: string;
            /** Will Call */
            will_call: string | null;
        };
        /** OpenApiChangesOut */
        OpenApiChangesOut: {
            /** Operations Added */
            operations_added: string[];
            /** Operations Removed */
            operations_removed: string[];
            /** Operations Changed */
            operations_changed: string[];
            /** Schemas Added */
            schemas_added: string[];
            /** Schemas Removed */
            schemas_removed: string[];
            /** Schemas Changed */
            schemas_changed: string[];
        };
        /** OperationOut */
        OperationOut: {
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Summary */
            summary: string | null;
        };
        /** PendingChangeOut */
        PendingChangeOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Fingerprint */
            fingerprint: string;
            /** Api Version */
            api_version: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            diff: components["schemas"]["ContractDiffOut"];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gen Width */
            gen_width: number;
            /** Gen Height */
            gen_height: number;
            /** Out Width */
            out_width: number;
            /** Out Height */
            out_height: number;
            /** Fps */
            fps: number;
            /** Min Scene Seconds */
            min_scene_seconds: number;
            /** Max Scene Seconds */
            max_scene_seconds: number;
            /** Clip Sound Volume */
            clip_sound_volume: number;
            /** Style Prefix */
            style_prefix: string | null;
            /** Prompt Suffix */
            prompt_suffix: string | null;
            /** Negative Prompt */
            negative_prompt: string | null;
            /** Cut Instructions */
            cut_instructions: string | null;
            /** Description Instructions */
            description_instructions: string | null;
            /** Script Text */
            script_text: string | null;
            voiceover: components["schemas"]["VoiceoverOut"] | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Voiceover Duration S */
            voiceover_duration_s: number | null;
            /** Has Script */
            has_script: boolean;
        };
        /**
         * ProjectUpdate
         * @description Only the fields that are sent are changed. The orientation cannot be changed.
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Gen Width */
            gen_width?: number | null;
            /** Gen Height */
            gen_height?: number | null;
            /** Out Width */
            out_width?: number | null;
            /** Out Height */
            out_height?: number | null;
            /** Fps */
            fps?: number | null;
            /** Min Scene Seconds */
            min_scene_seconds?: number | null;
            /** Max Scene Seconds */
            max_scene_seconds?: number | null;
            /** Clip Sound Volume */
            clip_sound_volume?: number | null;
            /** Style Prefix */
            style_prefix?: string | null;
            /** Prompt Suffix */
            prompt_suffix?: string | null;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Cut Instructions */
            cut_instructions?: string | null;
            /** Description Instructions */
            description_instructions?: string | null;
            /** Script Text */
            script_text?: string | null;
        };
        /**
         * ProposalOut
         * @description The proposal the scenes came from (the newest `plan_scenes` job that succeeded).
         */
        ProposalOut: {
            /** Job Id */
            job_id: number;
            /** Finished At */
            finished_at: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "ai" | "rule";
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Cache Hit Of Job Id */
            cache_hit_of_job_id: number | null;
            /** Model */
            model: string | null;
            usage: components["schemas"]["UsageOut"] | null;
            checks: components["schemas"]["ChecksOut"] | null;
            splitter: components["schemas"]["SplitterOut"] | null;
        };
        /**
         * ProposeScenesRequest
         * @description What the user has confirmed. Every flag is off unless sent.
         */
        ProposeScenesRequest: {
            /**
             * Run Again
             * @default false
             */
            run_again: boolean;
            /**
             * Accept Mismatch
             * @default false
             */
            accept_mismatch: boolean;
            /**
             * Discard Scenes With Inputs
             * @default false
             */
            discard_scenes_with_inputs: boolean;
        };
        /**
         * RenderOut
         * @description One finished render (a succeeded `render_final` job and its `final` asset).
         */
        RenderOut: {
            /** Asset Id */
            asset_id: number;
            /** Job Id */
            job_id: number;
            /** Url */
            url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Size Bytes */
            size_bytes: number;
            /** Clip Sound Volume */
            clip_sound_volume: number | null;
            /** Scene Count */
            scene_count: number;
            /** Muted Scene Count */
            muted_scene_count: number;
        };
        /** RendersOut */
        RendersOut: {
            job: components["schemas"]["JobSummary"] | null;
            /** Renders */
            renders: components["schemas"]["RenderOut"][];
        };
        /** SceneOut */
        SceneOut: {
            /** Id */
            id: number;
            /** Index */
            index: number;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Text */
            text: string;
            /**
             * Cut Source
             * @enum {string}
             */
            cut_source: "ai" | "rule" | "manual";
            /** Cut Note */
            cut_note: string | null;
            /** Has Inputs */
            has_inputs: boolean;
            /** First Word */
            first_word: number | null;
            /** Last Word */
            last_word: number | null;
            /** Scene Description */
            scene_description: string | null;
            /** Scene Description Source */
            scene_description_source: ("manual" | "ai") | null;
            /** First Frame Description */
            first_frame_description: string | null;
            /** Last Frame Description */
            last_frame_description: string | null;
            /** Frame Descriptions Source */
            frame_descriptions_source: ("manual" | "ai") | null;
            /** Description Job Id */
            description_job_id: number | null;
            /** Prompt */
            prompt: string | null;
            first_frame: components["schemas"]["FrameOut"] | null;
            last_frame: components["schemas"]["FrameOut"] | null;
            /** Missing */
            missing: ("description" | "first_frame" | "last_frame")[];
            /** Ready */
            ready: boolean;
            /** Use Clip Sound */
            use_clip_sound: boolean;
            /** Selected Clip Asset Id */
            selected_clip_asset_id: number | null;
            /** Target Frames */
            target_frames: number;
            clip_job: components["schemas"]["JobSummary"] | null;
            /** Clip Typical Run Seconds */
            clip_typical_run_seconds: number | null;
            /** Generate Blocked Reason */
            generate_blocked_reason: string | null;
            /** Takes */
            takes: components["schemas"]["TakeOut"][];
        };
        /**
         * SceneUpdate
         * @description The texts of a scene. Only the fields that are sent are changed, and null or blank
         *     clears one. A text that is saved becomes the author's (`manual`): a later AI draft never
         *     overwrites it.
         */
        SceneUpdate: {
            /** Scene Description */
            scene_description?: string | null;
            /** First Frame Description */
            first_frame_description?: string | null;
            /** Last Frame Description */
            last_frame_description?: string | null;
        };
        /**
         * SceneWordOut
         * @description One word of the script, as the scenes were cut from it.
         */
        SceneWordOut: {
            /** Index */
            index: number;
            /** Word */
            word: string;
            /** Paragraph */
            paragraph: number;
        };
        /** ScenesOut */
        ScenesOut: {
            job: components["schemas"]["JobSummary"] | null;
            proposal: components["schemas"]["ProposalOut"] | null;
            /** Scenes */
            scenes: components["schemas"]["SceneOut"][];
            /** Stale Reasons */
            stale_reasons: ("script_changed" | "voiceover_changed")[];
            llm: components["schemas"]["LlmInfoOut"];
            /** Words */
            words: components["schemas"]["SceneWordOut"][];
            /** Edit Blocked Reason */
            edit_blocked_reason: string | null;
            /** Ready Count */
            ready_count: number;
            /** Generate Ready Count */
            generate_ready_count: number;
            /** Max Parallel Generations */
            max_parallel_generations: number;
            /** Render Blocked Reason */
            render_blocked_reason: string | null;
            description_job: components["schemas"]["JobSummary"] | null;
            description_llm: components["schemas"]["LlmInfoOut"];
            /** Draft Blocked Reason */
            draft_blocked_reason: string | null;
            /** Draftable Count */
            draftable_count: number;
        };
        /** ScriptWordOut */
        ScriptWordOut: {
            /** Index */
            index: number;
            /** Word */
            word: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Matched */
            matched: boolean;
            /** Paragraph */
            paragraph: number;
        };
        /** SecretStatus */
        SecretStatus: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Is Set */
            is_set: boolean;
        };
        /** SelectTakeRequest */
        SelectTakeRequest: {
            /** Asset Id */
            asset_id: number;
        };
        /** ServerStatusOut */
        ServerStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "reachable" | "unreachable" | "unknown";
            /** Checked At */
            checked_at: string | null;
            /** Called Url */
            called_url: string | null;
            /** Error */
            error: string | null;
        };
        /** SettingItem */
        SettingItem: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Label */
            label: string;
            /** Help */
            help: string;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "string" | "integer";
            /** Value */
            value: string | number;
            /**
             * Source
             * @enum {string}
             */
            source: "saved" | "environment" | "built_in";
            /** Default */
            default: string | number;
            /** Env Var */
            env_var: string | null;
            /** Allow Blank */
            allow_blank: boolean;
            /** Min Value */
            min_value: number | null;
            /** Max Value */
            max_value: number | null;
            /** Will Call */
            will_call: string | null;
            /** Note */
            note: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SettingUpdate */
        SettingUpdate: {
            /** Value */
            value: number | string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Settings */
            settings: components["schemas"]["SettingItem"][];
            /** Secrets */
            secrets: components["schemas"]["SecretStatus"][];
        };
        /** SourceApprovalOut */
        SourceApprovalOut: {
            /** Name */
            name: string;
            /** Called Url */
            called_url: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "approved" | "unchanged" | "unstable" | "changed_again" | "unreachable" | "unreadable";
            /** Message */
            message: string | null;
            /** Fingerprint */
            fingerprint: string | null;
            diff: components["schemas"]["ContractDiffOut"] | null;
        };
        /** SourceCheckOut */
        SourceCheckOut: {
            /** Name */
            name: string;
            /** Called Url */
            called_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "changed" | "not_approved" | "unreachable" | "unreadable";
            /** Message */
            message: string | null;
            /** Approved Fingerprint */
            approved_fingerprint: string | null;
            /** Current Fingerprint */
            current_fingerprint: string | null;
        };
        /** SourceOverviewOut */
        SourceOverviewOut: {
            /** Name */
            name: string;
            /**
             * Base
             * @enum {string}
             */
            base: "gpu" | "transcription";
            /** Path */
            path: string;
            /** Called Url */
            called_url: string;
            approved: components["schemas"]["ApprovedSummaryOut"] | null;
            pending: components["schemas"]["PendingChangeOut"] | null;
            last_check: components["schemas"]["SourceCheckOut"] | null;
        };
        /** SplitterOut */
        SplitterOut: {
            /** Cuts Added */
            cuts_added: number;
            /** Cuts Removed */
            cuts_removed: number;
        };
        /** TagGroupOut */
        TagGroupOut: {
            /** Tag */
            tag: string;
            /** Operations */
            operations: components["schemas"]["OperationOut"][];
        };
        /**
         * TakeOut
         * @description One finished clip of a scene (a succeeded `generate_clip` job and its asset).
         */
        TakeOut: {
            /** Asset Id */
            asset_id: number;
            /** Job Id */
            job_id: number;
            /** Url */
            url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Seed */
            seed: number | null;
            /** Frame Count */
            frame_count: number | null;
            /** Target Frames */
            target_frames: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Audio Codec */
            audio_codec: string | null;
            /** Selected */
            selected: boolean;
            /** Out Of Date */
            out_of_date: boolean;
            /** Too Short */
            too_short: boolean;
        };
        /** ToolStatus */
        ToolStatus: {
            /** Ok */
            ok: boolean;
            /** Version */
            version?: string | null;
        };
        /** TranscriptCountsOut */
        TranscriptCountsOut: {
            /** Script Words */
            script_words: number;
            /** Matched */
            matched: number;
            /** Interpolated */
            interpolated: number;
            /** Spoken Words */
            spoken_words: number;
            /** Extra Spoken */
            extra_spoken: number;
        };
        /** TranscriptOut */
        TranscriptOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Provider */
            provider: string;
            /** Voiceover Asset Id */
            voiceover_asset_id: number | null;
            /** Script Words */
            script_words: components["schemas"]["ScriptWordOut"][];
            counts: components["schemas"]["TranscriptCountsOut"];
            /** Warnings */
            warnings: string[];
            /** Stale Reasons */
            stale_reasons: ("script_changed" | "voiceover_changed")[];
            /** Processing Time */
            processing_time: number | null;
        };
        /** TranscriptionOut */
        TranscriptionOut: {
            job: components["schemas"]["JobSummary"] | null;
            transcript: components["schemas"]["TranscriptOut"] | null;
        };
        /** UsageOut */
        UsageOut: {
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Reasoning Tokens */
            reasoning_tokens: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceoverOut */
        VoiceoverOut: {
            /** Asset Id */
            asset_id: number;
            /** Url */
            url: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Duration S */
            duration_s: number | null;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Something is not OK. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description A value breaks a rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A value breaks a rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_voiceover_api_projects__project_id__voiceover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is larger than the limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not sent as application/octet-stream. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is not an acceptable voiceover. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    save_setting_api_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingItem"];
                };
            };
            /** @description No setting has this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The value is not valid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_setting_api_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingItem"];
                };
            };
            /** @description No setting has this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_gpu_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionState"];
                };
            };
        };
    };
    test_connection_api_gpu_connection_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
        };
    };
    get_status_api_gpu_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuStatus"];
                };
            };
        };
    };
    save_contract_sources_api_gpu_contract_sources_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractSourcesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSourcesOut"];
                };
            };
            /** @description The value is not valid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_contract_sources_api_gpu_contract_sources_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSourcesOut"];
                };
            };
        };
    };
    get_contract_api_gpu_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOverviewOut"];
                };
            };
        };
    };
    approve_contract_api_gpu_contract_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                project_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No job has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No job has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The job is not in a state that allows it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The GPU server did not answer the cancel, so nothing changed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resubmit_job_api_jobs__job_id__resubmit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No job has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The job is not in a state that allows it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_transcription_api_projects__project_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The project has no voiceover or no script yet. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_transcription_api_projects__project_id__transcription_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionOut"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_scenes_api_projects__project_id__propose_scenes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProposeScenesRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The recording differs from the script, or scenes with inputs would be replaced, and the request did not confirm it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description There is no voiceover, script or current transcript yet, or the script is too long. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    draft_descriptions_api_projects__project_id__draft_descriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DraftDescriptionsRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description There are no scenes yet, a proposal is running, the scenes are out of date, there are too many, or every text was written by the user. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_scenes_api_projects__project_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_cut_api_projects__project_id__edit_cut_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CutEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A scene the edit changes has a description, frames or a clip, and the request did not confirm clearing them. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The cuts cannot be edited now (no scenes, a proposal running, out of date), or this edit is not possible. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_scene_api_projects__project_id__scenes__scene_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project, scene or frame has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A text is too long. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_frame_api_projects__project_id__scenes__scene_id__frames__slot__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
                slot: "first" | "last";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project, scene or frame has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is larger than the limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not sent as application/octet-stream. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file is not an acceptable frame. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_frame_api_projects__project_id__scenes__scene_id__frames__slot__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
                slot: "first" | "last";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project, scene or frame has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_preview_api_projects__project_id__frames__asset_id__preview_get: {
        parameters: {
            query: {
                width: number;
                height: number;
            };
            header?: never;
            path: {
                project_id: number;
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The frame as it will be sent, as a JPEG. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description The browser's copy is current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No project, scene or frame has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_clip_api_projects__project_id__scenes__scene_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No project or scene has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A clip cannot be generated now: the scene is not ready, is longer than the project's maximum, or the scenes are out of date or being replaced. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_ready_scenes_api_projects__project_id__generate_ready_scenes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateReadyOut"];
                };
            };
            /** @description No project or scene has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A clip cannot be generated now: the scene is not ready, is longer than the project's maximum, or the scenes are out of date or being replaced. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    select_take_api_projects__project_id__scenes__scene_id__select_take_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectTakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project or scene has this id, or the asset is not a finished clip of this scene. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_clip_sound_api_projects__project_id__scenes__scene_id__clip_sound_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClipSoundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No project or scene has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_render_api_projects__project_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The project cannot be rendered now: there is no voiceover or no scene, a scene has no clip or its clip is too short, or the scenes are out of date or being replaced. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_renders_api_projects__project_id__renders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RendersOut"];
                };
            };
            /** @description No project has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
