"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 23:06:08.729675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.types import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("server_content_hash", sa.Text(), nullable=True),
        sa.Column("api_version", sa.Text(), nullable=True),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("approved_at", UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "state IN ('approved', 'pending')", name=op.f("ck_api_snapshot_state_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_snapshot")),
    )
    with op.batch_alter_table("api_snapshot", schema=None) as batch_op:
        batch_op.create_index("idx_api_snapshot_source", ["source", "fetched_at"], unique=False)

    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("orientation", sa.Text(), nullable=False),
        sa.Column("gen_width", sa.Integer(), nullable=False),
        sa.Column("gen_height", sa.Integer(), nullable=False),
        sa.Column("out_width", sa.Integer(), nullable=False),
        sa.Column("out_height", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Integer(), server_default=sa.text("(24)"), nullable=False),
        sa.Column("min_scene_seconds", sa.REAL(), server_default=sa.text("(2.0)"), nullable=False),
        sa.Column("max_scene_seconds", sa.REAL(), server_default=sa.text("(6.0)"), nullable=False),
        sa.Column("style_prefix", sa.Text(), nullable=True),
        sa.Column("prompt_suffix", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("clip_sound_volume", sa.REAL(), server_default=sa.text("(0.2)"), nullable=False),
        sa.Column("cut_instructions", sa.Text(), nullable=True),
        sa.Column("script_text", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.Column("voiceover_asset_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "orientation IN ('portrait', 'landscape')", name=op.f("ck_project_orientation_valid")
        ),
        sa.ForeignKeyConstraint(
            ["voiceover_asset_id"],
            ["asset.id"],
            name=op.f("fk_project_voiceover_asset_id_asset"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting")),
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.REAL(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("provenance", sa.JSON(none_as_null=True), nullable=True),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('voiceover', 'frame', 'clip', 'final')", name=op.f("ck_asset_kind_valid")
        ),
        sa.CheckConstraint(
            "source IN ('upload', 'ai', 'derived')", name=op.f("ck_asset_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_asset_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.create_index("idx_asset_project", ["project_id"], unique=False)

    op.create_table(
        "transcript",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("words", sa.JSON(), nullable=False),
        sa.Column("script_words", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_transcript_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript")),
    )
    with op.batch_alter_table("transcript", schema=None) as batch_op:
        batch_op.create_index("idx_transcript_project", ["project_id"], unique=False)

    op.create_table(
        "scene",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.REAL(), nullable=False),
        sa.Column("end_s", sa.REAL(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("cut_source", sa.Text(), nullable=False),
        sa.Column("cut_note", sa.Text(), nullable=True),
        sa.Column("scene_description", sa.Text(), nullable=True),
        sa.Column("scene_description_source", sa.Text(), nullable=True),
        sa.Column("first_frame_asset_id", sa.Integer(), nullable=True),
        sa.Column("last_frame_asset_id", sa.Integer(), nullable=True),
        sa.Column("use_clip_sound", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("selected_clip_asset_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "cut_source IN ('ai', 'rule', 'manual')", name=op.f("ck_scene_cut_source_valid")
        ),
        sa.CheckConstraint(
            "scene_description_source IN ('manual', 'ai')",
            name=op.f("ck_scene_scene_description_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["first_frame_asset_id"],
            ["asset.id"],
            name=op.f("fk_scene_first_frame_asset_id_asset"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_frame_asset_id"],
            ["asset.id"],
            name=op.f("fk_scene_last_frame_asset_id_asset"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_scene_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selected_clip_asset_id"],
            ["asset.id"],
            name=op.f("fk_scene_selected_clip_asset_id_asset"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene")),
        sa.UniqueConstraint("project_id", "index", name=op.f("uq_scene_project_id")),
    )
    with op.batch_alter_table("scene", schema=None) as batch_op:
        batch_op.create_index("idx_scene_project", ["project_id"], unique=False)

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("phase", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_job_id", sa.Text(), nullable=True),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("result_asset_id", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", UTCDateTime(), nullable=True),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.Column("last_checked_at", UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "provider IN ('gpu', 'llm', 'local')", name=op.f("ck_job_provider_valid")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_job_status_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('transcribe', 'plan_scenes', 'generate_clip', 'render_final')",
            name=op.f("ck_job_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_job_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result_asset_id"],
            ["asset.id"],
            name=op.f("fk_job_result_asset_id_asset"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["scene.id"], name=op.f("fk_job_scene_id_scene"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index("idx_job_project", ["project_id"], unique=False)
        batch_op.create_index("idx_job_scene", ["scene_id"], unique=False)
        batch_op.create_index("idx_job_status", ["status"], unique=False)
        batch_op.create_index("idx_job_type_status", ["type", "status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("idx_job_type_status")
        batch_op.drop_index("idx_job_status")
        batch_op.drop_index("idx_job_scene")
        batch_op.drop_index("idx_job_project")

    op.drop_table("job")
    with op.batch_alter_table("scene", schema=None) as batch_op:
        batch_op.drop_index("idx_scene_project")

    op.drop_table("scene")
    with op.batch_alter_table("transcript", schema=None) as batch_op:
        batch_op.drop_index("idx_transcript_project")

    op.drop_table("transcript")
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_index("idx_asset_project")

    op.drop_table("asset")
    op.drop_table("setting")
    op.drop_table("project")
    with op.batch_alter_table("api_snapshot", schema=None) as batch_op:
        batch_op.drop_index("idx_api_snapshot_source")

    op.drop_table("api_snapshot")
    # ### end Alembic commands ###
